using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuGet.Protocol;
using Restaurant.Models;
using Restaurant.Models.Repositories;

namespace Restaurant.Controllers
{
    public class testController : Controller
    {

        public testController(IRepository<MasterOffer>repository)
        {
            Repository = repository;
        }

        public IRepository<MasterOffer> Repository { get; }







        // GET: testController1
        public ActionResult Index()
        {
            var item = new MasterOffer
            {
             // optional if it's auto-generated by the database
                MasterOfferTitle = "alalalallalalalaalallal",
                MasterOfferBreef = "2 Meals + 2 Drinks",
                MasterOfferDesc = "Enjoy a special combo for only 10.99 JOD. Valid all summer.",
                MasterOfferImageUrl = "/images/offers/summer-combo.jpg",

                // BaseEntity inherited properties
                IsActive = true,
                IsDeleted = false,
                CreatUser = "admin",
                CreatDate = DateTime.Now,
                EditUser = "admin",
                EditDate = DateTime.Now
            };


            //Repository.Add(item);

            //   Repository.Active(1);



            //update test
            //var updateitem = Repository.Find(1);
            //updateitem.MasterOfferTitle = "updateddataaa";
            //Repository.Update(1, updateitem);



            //****************
            //delete
          
            Repository.Delete(2, null);
            //*********************
            var data = Repository.View();
            var clientdata = Repository.ViewClient();
            return View(clientdata);
           
        }


    }
}
